# Generated by Django 3.2.5 on 2021-07-06 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='decription',
            new_name='description',
        ),
    ]
